pipeline {
  agent any
  environment {
    IMAGE = "mahek124/static-site:${env.BUILD_NUMBER}"
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build Docker Image') {
      steps {
        script {
          sh "docker build -t ${IMAGE} ."
        }
      }
    }
    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
          sh "docker push ${IMAGE}"
        }
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
          sh 'mkdir -p $HOME/.kube && cp $KUBECONFIG_FILE $HOME/.kube/config'
          // replace placeholder image tag in deployment.yaml and apply
          sh "sed -i 's#YOUR_DOCKERHUB_USERNAME/static-site:1.0#${IMAGE}#g' deployment.yaml || true"
          sh "kubectl apply -f deployment.yaml"
          sh "kubectl apply -f service.yaml"
        }
      }
    }
  }
}
